repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
   - id: flake8
     args: ['--ignore=E501,E203,E731,W503']
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      additional_dependencies: [click==8.0.2]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.990
  hooks:
    - id: mypy
      additional_dependencies: [types-dataclasses]
# - repo: https://github.com/pre-commit/mirrors-clang-format
#   rev: 'v12.0.1'
#   hooks:
#   - id: clang-format
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py37-plus]
    - id: nbqa-isort
      args: ['--profile=black']
    - id: nbqa-flake8
      args: ['--ignore=E501,E203,E302,E402,E731,W503']
